# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload-s3-parts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: S3 Uploader for GitHub Actions
        uses: Noelware/s3-action@1.3.1
        with:
          directories: '*'
          endpoint: https://s3.filebase.com
          bucket: all4vn
          access-key: ${{ secrets.FILEBASE_ACCESS_KEY }}
          secret-key: ${{ secrets.FILEBASE_SECRET_KEY }}
